### PR TITLE
store the solution inside the local storage

### PR DESCRIPTION
**Pull request by humorless**
testing

1. When a problem get loaded, on the solution block, it will not use the content of user-solution atom now. It use the content stored in the local-storage. 

2. When some content is inputed into the solution block, it will also get recorded in the local-storage.

### CODE REVIEW

**Comment by oxalorg** [comment]
Actually we should still use a global atom for the state of the solutions (or maybe even the entire app, this way it would be easier to switch to re-frame in the future if need be).

Then we can make the atom stay in sync with localstorage. This way we have a cleaner solution with all the benefits of atoms and no more localstorage calls all over the code.

One library to help do this would be: https://github.com/alandipert/storage-atom

What do you think about this approach? :thinking:

**Comment by humorless** [comment]
> Actually we should still use a global atom for the state of the solutions (or maybe even the entire app, this way it would be easier to switch to re-frame in the future if need be).
> 
> Then we can make the atom stay in sync with localstorage. This way we have a cleaner solution with all the benefits of atoms and no more localstorage calls all over the code.
> 
> One library to help do this would be: https://github.com/alandipert/storage-atom
> 
> What do you think about this approach? 🤔

It sounds interesting, let me do some experiments.

**Comment by humorless** [comment]
螢幕快照 2021-07-09 下午7 02 44
Now it store the solution using transit format.

**Comment by oxalorg** [comment]
LGTM! Thanks :tada:

**Pull request merged**
