### PR TITLE
Adding the restrictions data in problem view

### PR DESCRIPTION
**Pull request by pradeepbishnoi**
Just copied the style data from 4clojure on 'special restrictions'. We can tone it down to make it look right for new website format.

@oxalorg on a side note - I think should also use the website real state to. There is good amount of padding on left and right side of website. Also on the top we can save some padding spaces to bring the "write your code" section to viewing area. 

image

### CODE REVIEW

**Comment by oxalorg** [comment]
Super thanks for the PR!!

True I haven't focused too much on the design yet. Just implementing other features to make it a more smoother experience first! :)

Looks like some of the new changes have caused a conflict. Could you please rebase this, if not I'd be happy to do it before merging!

**Comment by pradeepbishnoi** [comment]
I have resolved it. However in the process, had resolved the conflict and merged into main branch (would have been better to push into a new branch). 

Now the pull request is showing 4 commits diff and multiple files 😞 
https://github.com/oxalorg/4ever-clojure/pull/14/files

However on comparing it is just showing the right one only.

image

**Comment by oxalorg** [comment]
That's fine I think on merge it will detect existing merges and skip over those :)

**Comment by oxalorg** [comment]
Super thanks for this!! :tada: 

tenor

**Pull request merged**
