### PR TITLE
enable paren matching

### PR DESCRIPTION
**Pull request by bobbicodes**
Thanks for giving such a nice example use of Nextjournal's Clojure-mode. I'd been meaning to try it out.

Adding this one CSS file makes the bracket matching work.

### CODE REVIEW

**Comment by oxalorg** [comment]
Thank you @porkostomus 😸🌸 , appreciate this and apologies for the delay! I'll deploy this over the weekend :)

**Comment by oxalorg** [comment]
This css file is actually overwriting a lot of regular styles and breaking the site layout 🙈 Maybe we should selectively only include css required for paren matching 🤔

**Comment by bobbicodes** [comment]
Ugh, they should be called "Mutually Non-composable Style Sheets"

**Comment by bobbicodes** [comment]
I have this solved locally, will make a new PR

**Pull request merged**
