### PR TITLE
feat: better problems modal

### PR DESCRIPTION
**Pull request by harismh**
Adds some opinionated tweaks to the problems modal.

I removed the close button at the bottom and replaced it with an "X" at the top right as I kept getting the primary action confused. For the primary action, it's now conditional based on the test results. If all tests pass, it shows a "Next problem #" button, otherwise it shows a return button.

I am still learning Clojure, so any suggestions on more idiomatic code is much appreciated!

Screenshot 2022-12-03 at 13 38 38
Screenshot 2022-12-03 at 13 38 44

### CODE REVIEW

**Comment by oxalorg** [comment]
Thanks for the PR @harismh 🙌 

Unfortunately we've moved away from the modal paradigm for test runs. We do use it only when all tests pass. Do you want to rebase it on main and still keep the `close` button in there? (The primary CTA on the modal can be to go to the next problem).

I'll be happy to do this if and merge it if you do not have the time available! Thanks again :)

**Comment by harismh** [comment]
Hey oxalorg, thanks for the review. The new site looks nice, and I enjoy the solution history. I'll try the rebase approach, but if I find the changes too extensive, I'll open a slimmed-down PR with just the close and CTA changes.

**Comment by harismh** [comment]
@oxalorg Finished rebasing and migrating changes. Let me know if further changes are needed.

**Comment by oxalorg** [comment]
LGTM! Thanks a lot @harismh 🥳

**Pull request merged**
