### PR TITLE
Fix problem where > disapppears when rendering editor

### PR DESCRIPTION
**Pull request by wooseopkim**
- We've been using `nextjournal.clojure-mode.test-utils/make-state`.
- That function uses `|` [for cursor position](https://github.com/nextjournal/clojure-mode/blob/db808194244bc14c12e578539b26123f3d6f9f90/src/nextjournal/clojure_mode/test_utils.cljs#L14-L15) and `<>` [for selection](https://github.com/nextjournal/clojure-mode/blob/db808194244bc14c12e578539b26123f3d6f9f90/src/nextjournal/clojure_mode/test_utils.cljs#L17-L21).
- Incomplete pairs of `<>` are discarded by the regular expression it uses, resulting in `->` or `->>` printed `-`.
- I thought that it is safe to skip the regex filtering  because AFAIK we don't store cursor positions nor selections.

### CODE REVIEW

**Comment by oxalorg** [comment]
Nice catch! I wasn't able to find this in my last exploration, thanks a lot for this 🕺 

I'll test this out tomorrow and merge it. Getting pretty late here now (almost 5am haha) 🙈

**Comment by wooseopkim** [comment]
~Looks much better. I'll close this. Thanks!~

**Comment by wooseopkim** [comment]
Oh I mistook this PR for another

**Comment by oxalorg** [comment]
LGTM! Thanks :3

**Pull request merged**
